# Generated by Django 4.2.26 on 2025-11-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(default='user@gmail.com', max_length=50)),
                ('user_image', models.URLField(default='empty')),
                ('user_password', models.CharField(max_length=12)),
            ],
        ),
    ]
